AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Image thumbnail generation service with S3 and DynamoDB

Parameters:
  S3BucketName:
    Type: String
    Description: Name of the S3 bucket for images
    Default: image-thumbnails-bucket

  AdminUsername:
    Type: String
    Description: Admin username for initial setup
    Default: admin

  AdminPassword:
    Type: String
    Description: Admin password for initial setup
    NoEcho: true

  DomainName:
    Type: String
    Description: Custom domain name for website and API
    Default: kill-snap.jeremy.ninja

  HostedZoneId:
    Type: String
    Description: Route53 Hosted Zone ID
    Default: ''

  CloudFrontCertificateArn:
    Type: String
    Description: ARN of ACM certificate in us-east-1 for CloudFront
    Default: ''

Resources:
  # DynamoDB table for image metadata
  ImageMetadataTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: kill-snap-ImageMetadata
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: ImageGUID
          AttributeType: S
        - AttributeName: Reviewed
          AttributeType: S
      KeySchema:
        - AttributeName: ImageGUID
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: ReviewedIndex
          KeySchema:
            - AttributeName: Reviewed
              KeyType: HASH
            - AttributeName: ImageGUID
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  # DynamoDB table for users
  UsersTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: kill-snap-Users
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: Username
          AttributeType: S
      KeySchema:
        - AttributeName: Username
          KeyType: HASH

  # DynamoDB table for review groups
  ReviewGroupsTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: kill-snap-ReviewGroups
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: ReviewID
          AttributeType: S
        - AttributeName: ImageGUID
          AttributeType: S
      KeySchema:
        - AttributeName: ReviewID
          KeyType: HASH
        - AttributeName: ImageGUID
          KeyType: RANGE

  # Lambda function for thumbnail generation
  ThumbnailFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ImageThumbnailGenerator
      Runtime: provided.al2023
      CodeUri: lambda/thumbnail/
      Handler: bootstrap
      MemorySize: 512
      Timeout: 60
      Environment:
        Variables:
          BUCKET_NAME: !Ref S3BucketName
          DYNAMODB_TABLE: !Ref ImageMetadataTable
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref S3BucketName
        - S3CrudPolicy:
            BucketName: !Ref S3BucketName
        - DynamoDBCrudPolicy:
            TableName: !Ref ImageMetadataTable

  # API Gateway REST API
  ImageReviewApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'*'"

  # Lambda function for API backend
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ImageReviewApi
      Runtime: provided.al2023
      CodeUri: lambda/api/
      Handler: bootstrap
      MemorySize: 256
      Timeout: 30
      Environment:
        Variables:
          BUCKET_NAME: !Ref S3BucketName
          IMAGE_TABLE: !Ref ImageMetadataTable
          USERS_TABLE: !Ref UsersTable
          REVIEW_GROUPS_TABLE: !Ref ReviewGroupsTable
          ADMIN_USERNAME: !Ref AdminUsername
          ADMIN_PASSWORD: !Ref AdminPassword
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref S3BucketName
        - S3CrudPolicy:
            BucketName: !Ref S3BucketName
        - DynamoDBCrudPolicy:
            TableName: !Ref ImageMetadataTable
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
        - DynamoDBCrudPolicy:
            TableName: !Ref ReviewGroupsTable
      Events:
        Login:
          Type: Api
          Properties:
            RestApiId: !Ref ImageReviewApi
            Path: /api/login
            Method: POST
        ListImages:
          Type: Api
          Properties:
            RestApiId: !Ref ImageReviewApi
            Path: /api/images
            Method: GET
        UpdateImage:
          Type: Api
          Properties:
            RestApiId: !Ref ImageReviewApi
            Path: /api/images/{imageId}
            Method: PUT
        DeleteImage:
          Type: Api
          Properties:
            RestApiId: !Ref ImageReviewApi
            Path: /api/images/{imageId}
            Method: DELETE
        GetPresignedUrl:
          Type: Api
          Properties:
            RestApiId: !Ref ImageReviewApi
            Path: /api/images/{imageId}/download
            Method: GET

  # CloudFront Origin Access Control
  CloudFrontOAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub ${AWS::StackName}-OAC
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  # CloudFront Distribution
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Condition: HasCustomDomain
    Properties:
      DistributionConfig:
        Enabled: true
        HttpVersion: http2
        DefaultRootObject: index.html
        Aliases:
          - !Ref DomainName
        ViewerCertificate:
          AcmCertificateArn: !Ref CloudFrontCertificateArn
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        Origins:
          # S3 Origin for website
          - Id: S3Origin
            DomainName: !Sub ${S3BucketName}-web.s3.${AWS::Region}.amazonaws.com
            OriginAccessControlId: !Ref CloudFrontOAC
            S3OriginConfig: {}
          # API Gateway Origin
          - Id: APIOrigin
            DomainName: !Sub ${ImageReviewApi}.execute-api.${AWS::Region}.amazonaws.com
            OriginPath: /prod
            CustomOriginConfig:
              HTTPSPort: 443
              OriginProtocolPolicy: https-only
              OriginSSLProtocols:
                - TLSv1.2
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
          Compress: true
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
        CacheBehaviors:
          # API behavior
          - PathPattern: /api/*
            TargetOriginId: APIOrigin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
              - PUT
              - POST
              - PATCH
              - DELETE
            CachedMethods:
              - GET
              - HEAD
            Compress: true
            ForwardedValues:
              QueryString: true
              Headers:
                - Authorization
                - Content-Type
              Cookies:
                Forward: all
            MinTTL: 0
            DefaultTTL: 0
            MaxTTL: 0
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html

  # Route53 Record for main domain
  DomainDnsRecord:
    Type: AWS::Route53::RecordSet
    Condition: HasHostedZone
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref DomainName
      Type: A
      AliasTarget:
        DNSName: !GetAtt CloudFrontDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2  # CloudFront hosted zone ID (constant)
        EvaluateTargetHealth: false

  # S3 Bucket Policy (must be after CloudFrontDistribution)
  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Condition: HasCustomDomain
    Properties:
      Bucket: !Sub ${S3BucketName}-web
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub arn:aws:s3:::${S3BucketName}-web/*
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}

Conditions:
  HasCustomDomain: !And
    - !Not [!Equals [!Ref DomainName, '']]
    - !Not [!Equals [!Ref CloudFrontCertificateArn, '']]
  HasHostedZone: !Not [!Equals [!Ref HostedZoneId, '']]

Outputs:
  BucketName:
    Description: S3 Bucket Name
    Value: !Ref S3BucketName

  WebsiteURL:
    Description: Website URL (Direct S3)
    Value: !Sub https://${S3BucketName}-web.s3.${AWS::Region}.amazonaws.com

  ApiEndpoint:
    Description: API Gateway endpoint URL (Direct)
    Value: !Sub https://${ImageReviewApi}.execute-api.${AWS::Region}.amazonaws.com/prod

  CustomDomainURL:
    Description: Custom Domain URL (CloudFront)
    Condition: HasCustomDomain
    Value: !Sub https://${DomainName}

  CloudFrontDistributionId:
    Description: CloudFront Distribution ID
    Condition: HasCustomDomain
    Value: !Ref CloudFrontDistribution

  ImageMetadataTableName:
    Description: Image Metadata DynamoDB Table Name
    Value: !Ref ImageMetadataTable

  UsersTableName:
    Description: Users DynamoDB Table Name
    Value: !Ref UsersTable

  ReviewGroupsTableName:
    Description: Review Groups DynamoDB Table Name
    Value: !Ref ReviewGroupsTable

  ThumbnailLambdaArn:
    Description: Thumbnail Lambda Function ARN
    Value: !GetAtt ThumbnailFunction.Arn

  ApiLambdaArn:
    Description: API Lambda Function ARN
    Value: !GetAtt ApiFunction.Arn
