AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Image thumbnail generation service with S3 and DynamoDB

Parameters:
  S3BucketName:
    Type: String
    Description: Name of the S3 bucket for images
    Default: image-thumbnails-bucket

Resources:
  # S3 Bucket for images with deletion protection
  ImageBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Ref S3BucketName
      VersioningConfiguration:
        Status: Enabled

  # DynamoDB table for image metadata
  ImageMetadataTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: ImageMetadata
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: ImageGUID
          AttributeType: S
      KeySchema:
        - AttributeName: ImageGUID
          KeyType: HASH

  # Lambda function for thumbnail generation
  ThumbnailFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: ImageThumbnailGenerator
      Runtime: provided.al2023
      CodeUri: lambda/
      Handler: bootstrap
      MemorySize: 512
      Timeout: 60
      Environment:
        Variables:
          BUCKET_NAME: !Ref ImageBucket
          DYNAMODB_TABLE: !Ref ImageMetadataTable
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref ImageBucket
        - S3CrudPolicy:
            BucketName: !Ref ImageBucket
        - DynamoDBCrudPolicy:
            TableName: !Ref ImageMetadataTable
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref ImageBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: .jpg

  # Permission for S3 to invoke Lambda
  ThumbnailFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ThumbnailFunction
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceArn: !GetAtt ImageBucket.Arn

Outputs:
  BucketName:
    Description: S3 Bucket Name
    Value: !Ref ImageBucket

  DynamoDBTableName:
    Description: DynamoDB Table Name
    Value: !Ref ImageMetadataTable

  LambdaFunctionArn:
    Description: Lambda Function ARN
    Value: !GetAtt ThumbnailFunction.Arn
